### ISSUE TITLE
Setup Cucumber.js and webdriver.io

### ISSUE THREAD

**Issue by philipbeadle** [eat-sleep-code-repeat/escr-shop#3]
Use this

https://github.com/webdriverio/cucumber-boilerplate

**Comment by philipbeadle** [comment]
Going to give this a crack :)

**Comment by pjagga** [comment]
Yeah I am trying to do the same.

1. Installed webdriverio
2. Installed cucumber ("cucumber": "^0.10.4",)
3. Installed webdriverio-cucumber-framework
4. setup the config wdio.cucumber.conf.js
5. try to run my test and getting the error(file attached).
